### ISSUE TITLE
One time trigger functions in e-paper.py (instead of starting the loop?)

### ISSUE THREAD

**Issue by iroQuai** [mgfcf/E-Paper-Calendar-with-iCal-sync-and-live-weather#13]
Is there a way to get back to the console after opening E-Paper.py? I'm testint out different settings and designs and it gets a bit annoying to open up a new putty window everytime I've refreshed the screen (thanks for the output to file btw, saves time!)

Maybe there's a button combo i don't know about to return to console? Or otherwise maybe a setting I could edit to stop the loop from starting?

**Comment by mgfcf** [comment]
You can use CTRL+C to interrupt a script that is running in the foreground. There might some points in the software, where using this does not stop it, due to some error catching going on, but in most cases that should work.

If you want to prevent the script from starting at boot, you should add the option `autostart=false` to `/etc/supervisor/conf.d/E-Paper.conf`.

I will add an option in the settings to run the script just once for convenience.

Max

**Comment by mgfcf** [comment]
Added the new option to the settings file. You may want to update your calendar software and add the new settings, `max_loop_count` and `run_on_hour`, to your personal settings file.

Max

**Comment by mgfcf** [comment]
I am going to close this topic for now. Feel free to open it up again or create a new issue!
