### ISSUE TITLE
Nothing written to display

### ISSUE THREAD

**Issue by bgree825** [mgfcf/E-Paper-Calendar-with-iCal-sync-and-live-weather#16]
Program runs successfully and design_exported.png is created, but nothing is rendered to the display. I've confirmed that the display works with the example programs that come from waveshare.

**Comment by mgfcf** [comment]
Hey there @Bengemon825 !

Please have a look at the settings.py and make sure that `render_to_display = True` is set at the bottom of the file.

What display are you using? I only own a tricolor 7.5" display from waveshare ([product site](https://www.waveshare.com/product/7.5inch-e-paper-hat-b.htm)).
Can you post the output of the program? You don't have to use supervisor to run the program. You can just execute `python3 E-Paper.py` in the Calendar directory (or use the same command as supervisor `sudo /usr/bin/python3.5 /home/pi/E-Paper-Master/Calendar/E-Paper.py`). This should print the output in the console for you to read out. After that, you can stop the execution by pressing CTRL+C. Otherwise you could take a look at the log files (`E-Paper.log` or `E-Paper-err.log` in case of errors) that can be found in `/home/pi/E-Paper-Master/`.

Have a nice day!
Max

**Comment by mgfcf** [comment]
Oh, and just as a side note:

Rendering the image to the display takes about 90secs on my setup (Raspberry Pi Zero W). This is due to the conversion of the image to the necessary binary format. So make sure that that you wait long enough. I would say at least 3 minutes. But the command line output gives some insight into that.

**Comment by mgfcf** [comment]
Since this issue is already one month old without any activity, I will close it for now. But feel free to reopen it if your issue persists!

Max
